### ISSUE TITLE
Angular 15 ng add dependency issue 'Packages installation failed'

### ISSUE THREAD

**Issue by a7medpa** [nestjs/ng-universal#942]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: webapp@0.0.0
npm ERR! Found: @angular/common@15.0.2
npm ERR!   @angular/common@"^15.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0 || ^13.0.0 || ^14.0.0" from @nestjs/ng-universal@6.1.0
npm ERR! node_modules/@nestjs/ng-universal
npm ERR!   @nestjs/ng-universal@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

`ng add @nestjs/ng-universal` fails with ✖ Packages installation failed, see above.

## Expected behavior

NestJS is added to Angular 15 project.

## Minimal reproduction of the problem with instructions

```
ng new webapp
cd webapp
ng add @nestjs/ng-universal
```
## What is the motivation / use case for changing the behavior?

Use the framework

## Environment

<pre><code>
Nest version: * (latest) and 6.0.1  (`ng add @nestjs/ng-universal` automatically picks 6.0.1 version for me)

 
For Tooling issues:
- Node version: 16.17.1 and 18.10.0  
- Platform: Windows  

Others:

</code></pre>

**Comment by abelfubu** [comment]
Same problem here

**Comment by kylerummens** [comment]
Any workaround for the time being?

**Comment by F4pl0** [comment]
Seems like no support for Angular 15 for now...

**Comment by mansern** [comment]
Hey folks, till the time the PR from bartlomiejgawel is not merged, you can use this NPM package: https://www.npmjs.com/package/ng-universal-15

This package supports Angular 15. 

PS. I used the PR of bartlomiejgawel and published my own package as a quick fix ;)

**Comment by F4pl0** [comment]
I think this has been fixed in `0.8.0`, I've also created a PR with this fix, and one other (bug crashed Angular development building process because of incorrect cache path) that has been done in said version, though PR hasn't been merged. Angular has been updated to 15 (from 14), but in some cases you may have to use the `--force` parameter to get around the possible minor version of Angular mismatch. It works for me in a NX workspace with Nest.js and Angular. I think there was no need for a temporary fork-y workaround, but also had same idea to make well-maintained version of this lib pre-`0.8.0`.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/ng-universal/pull/943
